//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18046
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecNote.Presentation.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal es() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecNote.Presentation.Web.Resources.es", typeof(es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a x.
        /// </summary>
        internal static string actor_delete {
            get {
                return ResourceManager.GetString("actor.delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Publicar Comentario.
        /// </summary>
        internal static string addComment {
            get {
                return ResourceManager.GetString("addComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a +.
        /// </summary>
        internal static string addComments {
            get {
                return ResourceManager.GetString("addComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjuntar Audio.
        /// </summary>
        internal static string attachAudio {
            get {
                return ResourceManager.GetString("attachAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Audio.
        /// </summary>
        internal static string audio_name {
            get {
                return ResourceManager.GetString("audio.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios.
        /// </summary>
        internal static string comments {
            get {
                return ResourceManager.GetString("comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Explorar.
        /// </summary>
        internal static string explore {
            get {
                return ResourceManager.GetString("explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Audio.
        /// </summary>
        internal static string newAudio {
            get {
                return ResourceManager.GetString("newAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Comentario.
        /// </summary>
        internal static string newComment_tile {
            get {
                return ResourceManager.GetString("newComment.tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electronico.
        /// </summary>
        internal static string placeholder_actor_email {
            get {
                return ResourceManager.GetString("placeholder.actor.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre y Apellidos.
        /// </summary>
        internal static string placeholder_actor_name {
            get {
                return ResourceManager.GetString("placeholder.actor.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar al Proyecto.
        /// </summary>
        internal static string project_actor_save {
            get {
                return ResourceManager.GetString("project.actor.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Participantes del Proyecto.
        /// </summary>
        internal static string project_actors {
            get {
                return ResourceManager.GetString("project.actors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Definiciones.
        /// </summary>
        internal static string project_definition {
            get {
                return ResourceManager.GetString("project.definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actores.
        /// </summary>
        internal static string project_description_actors {
            get {
                return ResourceManager.GetString("project.description.actors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema Actual.
        /// </summary>
        internal static string project_description_currentSystem {
            get {
                return ResourceManager.GetString("project.description.currentSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introducción.
        /// </summary>
        internal static string project_description_introduction {
            get {
                return ResourceManager.GetString("project.description.introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetivos.
        /// </summary>
        internal static string project_description_objectives {
            get {
                return ResourceManager.GetString("project.description.objectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Definiciones.
        /// </summary>
        internal static string project_descriptions {
            get {
                return ResourceManager.GetString("project.descriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a +.
        /// </summary>
        internal static string project_menu_new {
            get {
                return ResourceManager.GetString("project.menu.new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyectos.
        /// </summary>
        internal static string project_menu_title {
            get {
                return ResourceManager.GetString("project.menu.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Proyecto.
        /// </summary>
        internal static string project_name {
            get {
                return ResourceManager.GetString("project.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Proyecto.
        /// </summary>
        internal static string project_new_title {
            get {
                return ResourceManager.GetString("project.new.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a +.
        /// </summary>
        internal static string project_project_newAudio {
            get {
                return ResourceManager.GetString("project.project.newAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requisitos.
        /// </summary>
        internal static string project_requirements {
            get {
                return ResourceManager.GetString("project.requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funcionales.
        /// </summary>
        internal static string project_requirements_functional {
            get {
                return ResourceManager.GetString("project.requirements.functional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requisitos de información.
        /// </summary>
        internal static string project_requirements_information {
            get {
                return ResourceManager.GetString("project.requirements.information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Funcionales.
        /// </summary>
        internal static string project_requirements_nofunctional {
            get {
                return ResourceManager.GetString("project.requirements.nofunctional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Audios Asociados.
        /// </summary>
        internal static string project_view_audios {
            get {
                return ResourceManager.GetString("project.view.audios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actores.
        /// </summary>
        internal static string ProjectItemType_Actors {
            get {
                return ResourceManager.GetString("ProjectItemType.Actors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema actual.
        /// </summary>
        internal static string ProjectItemType_CurrentSystem {
            get {
                return ResourceManager.GetString("ProjectItemType.CurrentSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introducción.
        /// </summary>
        internal static string ProjectItemType_Introduction {
            get {
                return ResourceManager.GetString("ProjectItemType.Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetivos.
        /// </summary>
        internal static string ProjectItemType_Objetives {
            get {
                return ResourceManager.GetString("ProjectItemType.Objetives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funcionales.
        /// </summary>
        internal static string ProjectItemType_ReqFunctionals {
            get {
                return ResourceManager.GetString("ProjectItemType.ReqFunctionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a De Información.
        /// </summary>
        internal static string ProjectItemType_ReqInformations {
            get {
                return ResourceManager.GetString("ProjectItemType.ReqInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Funcionales.
        /// </summary>
        internal static string ProjectItemType_ReqNotFunctionals {
            get {
                return ResourceManager.GetString("ProjectItemType.ReqNotFunctionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar contraseña.
        /// </summary>
        internal static string recoveryPassword {
            get {
                return ResourceManager.GetString("recoveryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interesado.
        /// </summary>
        internal static string RoleType_Stakeholder {
            get {
                return ResourceManager.GetString("RoleType.Stakeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REC.note.
        /// </summary>
        internal static string systemName {
            get {
                return ResourceManager.GetString("systemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario (correo electronico).
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
