//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace RecNote.Entities.Projects
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ProjectRequirement
	{
		public virtual IEnumerable<ProjectItem> Functionals
		{
			get;
			set;
		}

		public virtual IEnumerable<ProjectItem> Informations
		{
			get;
			set;
		}

		public virtual IEnumerable<ProjectItem> NotFunctionals
		{
			get;
			set;
		}

		public ProjectRequirement()
		{
		}

	}
}

