//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace RecNote.Entities.Projects
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ProjectDefinition
	{
		public virtual IEnumerable<ProjectItem> Actors
		{
			get;
			set;
		}

		public virtual ProjectItem CurrentSystem
		{
			get;
			set;
		}

		public virtual ProjectItem Introducction
		{
			get;
			set;
		}

		public virtual IEnumerable<ProjectItem> Objetives
		{
			get;
			set;
		}

		public ProjectDefinition()
		{
		}

	}
}

