//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace RecNote.Entities.Projects
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public enum ProjectItemType : int
	{
		Actors,
		CurrentSystem,
		Introduction,
		Objetives,
		ReqFunctionals,
		ReqInformations,
		ReqNotFunctionals,
	}
}
