//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace RecNote.Entities.Projects
{
	using RecNote.Entities;
	using RecNote.Entities.Users;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Project : Base
	{
		public virtual IEnumerable<Actor> Actors
		{
			get;
			set;
		}

		public virtual ProjectDefinition Definition
		{
			get;
			set;
		}

		public virtual bool IsTemporal
		{
			get;
			set;
		}

		public virtual string Name
		{
			get;
			set;
		}

		public virtual User Owner
		{
			get;
			set;
		}

		public virtual ProjectRequirement Requirements
		{
			get;
			set;
		}

		public virtual ProjectStateType State
		{
			get;
			set;
		}

		public Project()
		{
		}

	}
}

