//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace RecNote.Entities.Projects
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ProjectItemComment
	{
		public virtual string Message
		{
			get;
			set;
		}

		public virtual DateTime Time
		{
			get;
			set;
		}

		public virtual string UserID
		{
			get;
			set;
		}

		public ProjectItemComment()
		{
		}

	}
}

