//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace RecNote.Entities.Files
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class AudioFile : File
	{
		public virtual string AlterPath
		{
			get;
			set;
		}

		public virtual string AudioID
		{
			get;
			set;
		}

		public virtual IEnumerable<bool> Finger
		{
			get;
			set;
		}

		public AudioFile()
		{
		}

	}
}

