//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace RecNote.Entities.Files
{
	using RecNote.Entities;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class File : Base
	{
		public virtual string ContentType
		{
			get;
			set;
		}

		public virtual string FullPath
		{
			get;
			set;
		}

		public virtual string Name
		{
			get;
			set;
		}

		public virtual Int64 Size
		{
			get;
			set;
		}

		public virtual string Url
		{
			get;
			set;
		}

		public File()
		{
		}

	}
}

